name = "Chmy"
uuid = "33a72cf0-4690-46d7-b987-06506c2248b9"
version = "0.2.0"
authors = ["Ivan Utkin <iutkin@ethz.ch> and contributors"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.10"
Adapt = "4"
KernelAbstractions = "0.9"
StaticArrays = "1.9"
